### ISSUE TITLE
Correction for obesity?

### ISSUE THREAD

**Issue by nradov** [dmcalli2/covid19_yll_final#1]
While the analysis corrects for some comorbidities, I didn't see any mention of obesity. After age, obesity appears to be the most significant risk factor for severe COVID-19 symptoms. And obesity also reduces life expectancy. Is it possible that this causes YLL to be overestimated?
https://www.medrxiv.org/content/10.1101/2020.04.08.20057794v1

**Comment by dmcalli2** [comment]
Possibly, but I think it is unlikely to have a large effect for three reasons:-
1. The RR for obesity on mortality is not that large
2. We have measures of some of the downstream effects of obesity, hypertension and diabetes
3. Obesity is already pretty common in the population, therefore it is, to this extent, included in the survival model

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by nradov** [comment]
Obesity by itself does have a significant impact on YLL.
https://pubmed.ncbi.nlm.nih.gov/30283076/
https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001673

**Comment by dmcalli2** [comment]
It is the HR that matters for the modelling. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4855514<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4855514/>

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by dmcalli2** [comment]
Decided to direct scientific discussion (rather than coding etc related) to the journal comments section
